require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'SlackRNChatApp' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end

  # Pods for SlackRNChatApp

  target 'SlackRNChatAppTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'SlackRNChatApp-tvOS' do
  # Pods for SlackRNChatApp-tvOS

  target 'SlackRNChatApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

install! 'cocoapods', :deterministic_uuids => false, :integrate_targets => false